// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTpW1esSbeySb1Huoc2gh17OkskMpfiE',
    appId: '1:170815845359:web:1d878857e7960e25effc1a',
    messagingSenderId: '170815845359',
    projectId: 'dx-lifestation',
    authDomain: 'dx-lifestation.firebaseapp.com',
    databaseURL: 'https://dx-lifestation-default-rtdb.firebaseio.com',
    storageBucket: 'dx-lifestation.firebasestorage.app',
    measurementId: 'G-27WVXMBDBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7sp2VT6fhQiRdUsj_RwdJ5lh38IFcxI',
    appId: '1:170815845359:android:ad46a94efb65965feffc1a',
    messagingSenderId: '170815845359',
    projectId: 'dx-lifestation',
    databaseURL: 'https://dx-lifestation-default-rtdb.firebaseio.com',
    storageBucket: 'dx-lifestation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQIHReKxZvUm00Fuw1Qeiay08y8zquLqk',
    appId: '1:170815845359:ios:8b842923192fc15aeffc1a',
    messagingSenderId: '170815845359',
    projectId: 'dx-lifestation',
    databaseURL: 'https://dx-lifestation-default-rtdb.firebaseio.com',
    storageBucket: 'dx-lifestation.firebasestorage.app',
    iosBundleId: 'com.example.dxCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQIHReKxZvUm00Fuw1Qeiay08y8zquLqk',
    appId: '1:170815845359:ios:8b842923192fc15aeffc1a',
    messagingSenderId: '170815845359',
    projectId: 'dx-lifestation',
    databaseURL: 'https://dx-lifestation-default-rtdb.firebaseio.com',
    storageBucket: 'dx-lifestation.firebasestorage.app',
    iosBundleId: 'com.example.dxCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkTpW1esSbeySb1Huoc2gh17OkskMpfiE',
    appId: '1:170815845359:web:b73ca344dc354c3feffc1a',
    messagingSenderId: '170815845359',
    projectId: 'dx-lifestation',
    authDomain: 'dx-lifestation.firebaseapp.com',
    databaseURL: 'https://dx-lifestation-default-rtdb.firebaseio.com',
    storageBucket: 'dx-lifestation.firebasestorage.app',
    measurementId: 'G-F0XW7XCG3W',
  );
}
